### ISSUE TITLE
No error is produced

### ISSUE THREAD

**Issue by LWEdslev** [parker-codes/todo_by#8]
I tried 
```rust
use todo_by::todo_by;

todo_by!("2020-06-01");

fn main() {}
```
I expected an error but it compiles fine on stable and nightly.
If I include the macro in an expression I get the expected error, like this:
```rust
use todo_by::todo_by;

fn main() {
    &todo_by!("2020-06-01");
}
```
I get multiple errors but one of them is `error: TODO by Jun 1, 2020 has passed`

**Comment by parker-codes** [comment]
Can you attach the `todo_by` line to `main()` by removing the extra line in between? See if that solves the issue.

**Comment by LWEdslev** [comment]
It does not.
I also tried the example from the readme, and calling the function `my_function` to avoid unused, but it still compiles fine:
```rust
use todo_by::todo_by;

todo_by!("2023-06-01"); 
fn my_function() {
    // TODO: Implement this function by June 1st, 2023
}

fn main() {
    my_function();
}
```
```
rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)
```

**Comment by parker-codes** [comment]
So back in https://github.com/parker-codes/todo_by/pull/5 I changed this lib to not fail, because it was damaging reproducible builds. In the future we could expose more control, but the point was to highlight areas to change, not to break project dependency trees. 😄

Edit: You should be seeing an error in your editor, if it has the proper diagnostics enabled.

**Comment by LWEdslev** [comment]
That makes sense and I agree with that choice, I do see the error in VSCode. 
It is however not consistent with the documentation which I think should be updated to reflect this.

**Comment by parker-codes** [comment]
Thank you for pointing that out - it should definitely be updated.
